# Generated by Django 6.0.3 on 2026-04-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_failed_login_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('EMPLOYEE', 'Employee'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
