# Generated by Django 6.0.3 on 2026-04-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_remove_bankaccount_is_active_bankaccount_aadhaar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('WITHDRAW', 'Withdraw'), ('TRANSFER', 'Transfer'), ('DEPOSIT', 'Deposit'), ('LOAN_CREDIT', 'Loan Credit')], max_length=20),
        ),
    ]
