# Generated by Django 6.0.3 on 2026-04-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_alter_loan_status_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('WITHDRAW', 'Withdraw'), ('TRANSFER', 'Transfer'), ('DEPOSIT', 'Deposit'), ('LOAN_CREDIT', 'Loan Credited')], max_length=20),
        ),
    ]
