# Generated by Django 6.0.3 on 2026-03-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='maturity_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
